<a href="https://colab.research.google.com/github/showmik121/Genetivie_AI/blob/main/Pytorch_Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd

In [37]:
import torch

In [3]:
x=torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [5]:
y=x**2
y

tensor(9., grad_fn=<PowBackward0>)

In [6]:
y.backward()

In [ ]:
x.grad

In [16]:
x=torch.tensor(3.0,requires_grad=True)
y=x**2
z=torch.sin(y)
# x->sq->y->sin->z
# forward

In [ ]:
z

In [ ]:
y

In [17]:
# backward direction
z.backward()

In [ ]:
x.grad

# tranning

In [3]:
# inputs
x = torch.tensor([6, 7])   #input feature
y = torch.tensor([0.0,0.0])  #true label binary
w = torch.tensor(1.0, requires_grad=True) #weight
b = torch.tensor(0.0, requires_grad=True)  #Bias

In [4]:
z=w*x+b
z

tensor([6., 7.], grad_fn=<AddBackward0>)

In [5]:
y_pred=torch.sigmoid(z)
y_pred

tensor([0.9975, 0.9991], grad_fn=<SigmoidBackward0>)

In [7]:
# Use the binary_cross_entropy function from torch.nn.functional
loss = torch.nn.functional.binary_cross_entropy(y_pred, y)  # y now has the same shape as y_pred
loss

tensor(6.5017, grad_fn=<BinaryCrossEntropyBackward0>)

In [8]:
loss.backward()

In [ ]:
print(w.grad)
print(b.grad)

**vector input**

In [10]:
x=torch.tensor([1.0,2.0,3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [12]:
y=(x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [13]:
y.backward()

In [14]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

**clearing grad**

In [32]:
# clearing grad
x=torch.tensor(2.0,requires_grad=True)

In [ ]:
y=x**2
y.backward()
x.grad
# gradian acumolated
# so we need to gradian clean

In [ ]:
x.grad.zero_()

**How to disable gradient traking:**

____somethimes there are comes to a situation that we donot need to calculate darivative_

**in timeas of prediction we donot need gradient tracking**

In [38]:
# gradient traking disable
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [39]:
y=x**2
y

tensor(4., grad_fn=<PowBackward0>)

In [40]:
y.backward()

In [41]:
x.grad

tensor(4.)

In [42]:
x.requires_grad_(False)
# if we use (_) it inplace change

tensor(2.)

In [45]:
y=x**2
y

tensor(4.)

**OR**

we can use "detach" function

In [46]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [47]:
z=x.detach()
z

tensor(2.)

In [49]:
y=z**2
y

tensor(4.)

**OR**

using---"with torch.no_grad()"

In [52]:
x=torch.tensor(2.0,requires_grad=True)
x

tensor(2., requires_grad=True)

In [54]:
with torch.no_grad():
  a=x**2


In [55]:
a

tensor(4.)