<a href="https://colab.research.google.com/github/showmik121/Genetivie_AI/blob/main/Tensor_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Torch

**Import torch**

In [2]:
import torch
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")
print(device)

**Create a tensor**

In [ ]:
a=torch.empty(2,3)

In [ ]:
type(a)

In [ ]:
# using zeros
torch.zeros(2,3)

In [ ]:
#using ones
torch.ones(2,3)

In [ ]:
#using rand
torch.rand(2,3)

In [ ]:
# using seed
torch.manual_seed(100)
torch.rand(2,3)

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)
# same random value

In [ ]:
torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
# arange
torch.arange(0,20,2)

In [ ]:
# linspace
torch.linspace(0,10,10)

In [ ]:
# eye- indentiti matrix
torch.eye(5)

In [ ]:
# full
torch.full((3,3),5)

**Tensor Shapes**

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# tensor shape copy
torch.empty_like(x)

In [ ]:
torch.zeros_like(x)


In [ ]:
torch.rand_like(x,dtype=torch.float32)

**Tensor Data Type**

In [ ]:
# find data type
x.dtype


In [ ]:
# assign data type
x=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)
x

In [ ]:
x=torch.tensor([[1.0,3.0,4.0],[2.0,4.0,5.0]],dtype=torch.int32)
x

In [ ]:
# to()-change data type
x.to(torch.float64)

# Mathematical Operation

In [ ]:
x=torch.rand(2,2)
x

In [ ]:
# addition
x+2

In [ ]:
# sunstruction
x-2

In [ ]:
# multification
x*3

In [ ]:
# division
x/3

In [ ]:
# int division
x*3//3

In [ ]:
b=torch.rand(2,2)
b

In [ ]:
# add
torch.add(x,b)

In [ ]:
# sub
# multiply
torch.multiply(x,b)

In [ ]:
c=torch.tensor([[1,-2],[-3,4]])
c

In [ ]:
# abs
torch.abs(c)

In [ ]:
# neg
torch.neg(c)

In [ ]:
d=torch.tensor([1.2,3.5,1.7,3.9])
d

In [ ]:
# round
torch.round(d)


In [ ]:
# ceil
torch.ceil(d)

In [ ]:
# clamp
torch.clamp(d,min=2,max=3)

**Reduction**

In [ ]:
e=torch.randint(size=(2,3),low=0,high=100)
e

In [ ]:
# sum
torch.sum(e)

In [ ]:
# sum among colum
torch.sum(e,dim=0)

In [ ]:
# sum among rows
torch.sum(e,dim=1)

In [ ]:
# mean
torch.mean(e.type(torch.float32)) # Change the data type of tensor 'e' to float32 before calculating the mean

In [ ]:
torch.mean(e.type(torch.float32),dim=0)

In [ ]:
# argmax
torch.argmax(e)

tensor(5)

In [ ]:
# argmin
torch.argmin(e)

tensor(0)

# Matrix Operation

In [ ]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

In [ ]:
# matrix multiplication
torch.matmul(f,g)

In [ ]:
#  dot product
vector1=torch.tensor([1,2,3])
vector2=torch.tensor([4,5,6])
torch.dot(vector1,vector2)

In [ ]:
# sigmoid
torch.sigmoid(torch.tensor([1.0,2.0,4.0]))

In [ ]:
# softmax
torch.softmax(torch.tensor([1.0,2.0,4.0]),dim=0)

In [ ]:
# relu
torch.relu(torch.tensor([1.0,-2.0,4.0]))

# Inplace Operatin

In [ ]:
m=torch.tensor([1.9,3.0,4.0])
m

tensor([1.9000, 3.0000, 4.0000])

In [ ]:
torch.softmax(m,dim=0)

tensor([0.3303, 0.3318, 0.3379])

In [ ]:
# calculate softmax and get the result as a new tensor
m = m.softmax(dim=0) # assign the result to update 'm' with the softmax values
m

tensor([0.3303, 0.3318, 0.3379])

In [ ]:
# inplace
m.relu_()

tensor([0.0822, 0.2468, 0.6710])

**Copy a tensor**

In [ ]:
# clone
a=torch.tensor([[1,2,3],[4,5,6]])
b=a.clone()
b

# Tensor operation on GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device=torch.device("cuda")

In [ ]:
torch.rand(2,3).to(device)

# Reshapping Tensor

In [ ]:
a=torch.ones(4,4)
a

In [ ]:
# reshape
a.reshape(2,2,2,2)

In [ ]:
# flatten
a.flatten()

In [ ]:
b=torch.rand(2,3,4)
b

In [ ]:
# permute
b.permute(2,0,1).shape

In [ ]:
# unsqueeze
# image size
c=torch.rand(3,224,224)
c.unsqueeze(0).shape

In [ ]:
# squeeze
d=torch.rand(1,3,224,224)
d.squeeze(0).shape
# delet 0 dimention

# NumPy and PyTorch

In [21]:
import numpy as np


In [22]:
a=torch.tensor([1,2,3,4])

In [25]:
b=a.numpy()
b

array([1, 2, 3, 4])

In [26]:
type(b)

numpy.ndarray

In [ ]:
c=np.array([1,2,3])
c

In [29]:
torch.from_numpy(c) # Use 'from_numpy' instead of 'form_numpy' to convert the NumPy array 'c' to a PyTorch tensor.

tensor([1, 2, 3])